version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rubberduck_dev
      DB_HOST: db
      MIX_ENV: dev
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rubberduck_dev

